(ns beerpressure.db.beer-test
  (:require [clojure.test :refer :all]
            [beerpressure.handler :refer :all]
            [beerpressure.db.common-test :refer :all]))

(use-fixtures :once db-setup)

(deftest test-resolve-beer
  (testing "beer(id: 1) - 1 brewery"
    (let [graphql-query (long-str "{"
                                  "  beer(id: 1) {"
                                  "    id"
                                  "    name"
                                  "    description"
                                  "    ibu"
                                  "    alcoholPercent"
                                  "    imagePath"
                                  "    breweries {"
                                  "      id"
                                  "      name"
                                  "      description"
                                  "      imagePath"
                                  "    }"
                                  "  }"
                                  "}")
          expected-response (long-str "{"
                                      "  \"data\": {"
                                      "    \"beer\": {"
                                      "      \"id\": 1,"
                                      "      \"name\": \"Molson Canadian\","
                                      "      \"description\": \"Une bière avec une feuille d'érable dessus...\","
                                      "      \"ibu\": 15,"
                                      "      \"alcoholPercent\": 5.0,"
                                      "      \"imagePath\": \"https:\\/\\/decrescente.net\\/images\\/suppliers\\/millercoors\\/molson\\/molson-canadian\\/canadian-bottle-lg.png\","
                                      "      \"breweries\": ["
                                      "        {"
                                      "          \"id\": 1,"
                                      "          \"name\": \"MolsonCoors\","
                                      "          \"description\": \"Ils ne font de la marde comme bière.\","
                                      "          \"imagePath\": \"https:\\/\\/images.radio-canada.ca\\/q_auto,w_1250\\/v1\\/ici-info\\/16x9\\/molson-montreal-notre-dame.jpg\""
                                      "        }"
                                      "      ]"
                                      "    }"
                                      "  }"
                                      "}")
          response (execute-graphql-query graphql-query)]
      (is (is-data-equal response expected-response))))
  (testing "beer(id: 5) - 2 breweries"
    (let [graphql-query (long-str "{"
                                  "  beer(id: 5) {"
                                  "    id"
                                  "    breweries {"
                                  "      id"
                                  "      name"
                                  "      description"
                                  "      imagePath"
                                  "    }"
                                  "  }"
                                  "}")
          expected-response (long-str "{"
                                      "  \"data\": {"
                                      "    \"beer\": {"
                                      "      \"id\": 5,"
                                      "      \"breweries\": ["
                                      "        {"
                                      "          \"id\": 5,"
                                      "          \"name\": \"Siboire\","
                                      "          \"description\": \"Une brasserie de Sherbrooke.\","
                                      "          \"imagePath\": \"http:\\/\\/www.ambq.ca\\/mod\\/file\\/MembreFile\\/c45147dee729311ef5b5c3003946c48f.png\""
                                      "        },"
                                      "        {"
                                      "          \"id\": 6,"
                                      "          \"name\": \"SherBroue\","
                                      "          \"description\": \"Génie Sherbrooke!!!\","
                                      "          \"imagePath\": \"http:\\/\\/sherbroue.ca\\/accueil\\/wp-content\\/uploads\\/2012\\/02\\/Couverture-Facebook-1.jpg\""
                                      "        }"
                                      "      ]"
                                      "    }"
                                      "  }"
                                      "}")
          response (execute-graphql-query graphql-query)]
      (is (is-data-equal response expected-response)))))

(deftest test-resolve-beers
  (testing "beers(skip: 3, first: 2)"
    (let [graphql-query (long-str "{"
                                  "  beers(skip: 3, first: 2) {"
                                  "    id"
                                  "    name"
                                  "    description"
                                  "    ibu"
                                  "    alcoholPercent"
                                  "    imagePath"
                                  "    breweries {"
                                  "      id"
                                  "      name"
                                  "      description"
                                  "      imagePath"
                                  "    }"
                                  "  }"
                                  "}")
          expected-response (long-str "{"
                                      "  \"data\": {"
                                      "    \"beers\": ["
                                      "      {"
                                      "        \"id\": 4,"
                                      "        \"name\": \"Péché Mortel\","
                                      "        \"description\": \"La seule bonne bière du site.\","
                                      "        \"ibu\": 76,"
                                      "        \"alcoholPercent\": 9.5,"
                                      "        \"imagePath\": \"http:\\/\\/images.lpcdn.ca\\/641x427\\/201703\\/31\\/1377153.jpg\","
                                      "        \"breweries\": ["
                                      "          {"
                                      "            \"id\": 4,"
                                      "            \"name\": \"Dieu du Ciel!\","
                                      "            \"description\": \"Enfin!! Une brasserie qui fait de la bonne bière.\","
                                      "            \"imagePath\": \"http:\\/\\/theatregillesvigneault.com\\/wp-content\\/uploads\\/2017\\/03\\/DIEU-DU-CIEL.jpg\""
                                      "          }"
                                      "        ]"
                                      "      },"
                                      "      {"
                                      "        \"id\": 5,"
                                      "        \"name\": \"Ingénieuse\","
                                      "        \"description\": \"Bière collaborative.\","
                                      "        \"ibu\": 17,"
                                      "        \"alcoholPercent\": 5.1,"
                                      "        \"imagePath\": \"https:\\/\\/cdn.narcity.com\\/uploads\\/249500_90d9f57c70a3e15b6e0a08e67dcf1d944038212a.jpg\","
                                      "        \"breweries\": ["
                                      "          {"
                                      "            \"id\": 5,"
                                      "            \"name\": \"Siboire\","
                                      "            \"description\": \"Une brasserie de Sherbrooke.\","
                                      "            \"imagePath\": \"http:\\/\\/www.ambq.ca\\/mod\\/file\\/MembreFile\\/c45147dee729311ef5b5c3003946c48f.png\""
                                      "          },"
                                      "          {"
                                      "            \"id\": 6,"
                                      "            \"name\": \"SherBroue\","
                                      "            \"description\": \"Génie Sherbrooke!!!\","
                                      "            \"imagePath\": \"http:\\/\\/sherbroue.ca\\/accueil\\/wp-content\\/uploads\\/2012\\/02\\/Couverture-Facebook-1.jpg\""
                                      "          }"
                                      "        ]"
                                      "      }"
                                      "    ]"
                                      "  }"
                                      "}")
          response (execute-graphql-query graphql-query)]
      (is (is-data-equal response expected-response)))))
