(ns beerpressure.db.profile-test
  (:require [clojure.test :refer :all]
            [beerpressure.handler :refer :all]
            [beerpressure.db.common-test :refer :all]))

(use-fixtures :once db-setup-with-logged-user-fixture)

(deftest test-resolve-tags
  (testing "tags(skip: 1, first: 2, orderBy: NAME, orderType: ASC) "
    (let [graphql-query (long-str "{"
                                  "	profile(cip: \\\"mahm1904\\\") {"
                                  "		user {"
                                  "			cip"
                                  "			name"
                                  "			surname"
                                  "		}"
                                  "		breweryReviewedBy {"
                                  "			brewery {"
                                  "				id"
                                  "				name"
                                  "				description"
                                  "				imagePath"
                                  "				tags {"
                                  "					id"
                                  "					name"
                                  "				}"
                                  "				rating"
                                  "			}"
                                  "			review {"
                                  "				idBreweryReview"
                                  "				user {"
                                  "					cip"
                                  "					name"
                                  "					surname"
                                  "				}"
                                  "				idBrewery"
                                  "				title"
                                  "				content"
                                  "				imagePath"
                                  "				rating"
                                  "				time"
                                  "				thumbsups {"
                                  "					user {"
                                  "						cip"
                                  "						name"
                                  "						surname"
                                  "					}"
                                  "				}"
                                  "			}"
                                  "		}"
                                  "		beerReviewedBy {"
                                  "			beer {"
                                  "				id"
                                  "				name"
                                  "				description"
                                  "				ibu"
                                  "				alcoholPercent"
                                  "				imagePath"
                                  "				breweries {"
                                  "					id"
                                  "					name"
                                  "					description"
                                  "					imagePath"
                                  "					tags {"
                                  "						id"
                                  "						name"
                                  "					}"
                                  "					rating"
                                  "				}"
                                  "				tags {"
                                  "					id"
                                  "					name"
                                  "				}"
                                  "				rating"
                                  "				style {"
                                  "					id"
                                  "					name"
                                  "				}"
                                  "			}"
                                  "			review {"
                                  "				idBeerReview"
                                  "				user {"
                                  "					cip"
                                  "					name"
                                  "					surname"
                                  "				}"
                                  "				idBeer"
                                  "				title"
                                  "				content"
                                  "				imagePath"
                                  "				rating"
                                  "				time"
                                  "				thumbsups {"
                                  "					user {"
                                  "						cip"
                                  "						name"
                                  "						surname"
                                  "					}"
                                  "				}"
                                  "			}"
                                  "		}"
                                  "		breweryReviewsCommentedBy {"
                                  "			breweryReview {"
                                  "				idBreweryReview"
                                  "				user {"
                                  "					cip"
                                  "					name"
                                  "					surname"
                                  "				}"
                                  "				idBrewery"
                                  "				title"
                                  "				content"
                                  "				imagePath"
                                  "				rating"
                                  "				time"
                                  "				thumbsups {"
                                  "					user {"
                                  "						cip"
                                  "						name"
                                  "						surname"
                                  "					}"
                                  "				}"
                                  "			}"
                                  "			comment {"
                                  "				idBreweryReviewComment"
                                  "				idBreweryReview"
                                  "				user {"
                                  "					cip"
                                  "					name"
                                  "					surname"
                                  "				}"
                                  "				content"
                                  "				time"
                                  "			}"
                                  "		}"
                                  "		beerReviewsCommentedBy {"
                                  "			beerReview {"
                                  "				idBeerReview"
                                  "				user {"
                                  "					cip"
                                  "					name"
                                  "					surname"
                                  "				}"
                                  "				idBeer"
                                  "				title"
                                  "				content"
                                  "				imagePath"
                                  "				rating"
                                  "				time"
                                  "				thumbsups {"
                                  "					user {"
                                  "						cip"
                                  "						name"
                                  "						surname"
                                  "					}"
                                  "				}"
                                  "			}"
                                  "			comment {"
                                  "				idBeerReviewComment"
                                  "				idBeerReview"
                                  "				user {"
                                  "					cip"
                                  "					name"
                                  "					surname"
                                  "				}"
                                  "				content"
                                  "				time"
                                  "			}"
                                  "		}"
                                  "		breweryReviewsThumbsupBy {"
                                  "			idBreweryReview"
                                  "     user {"
                                  "       cip"
                                  "       name"
                                  "       surname"
                                  "     }"
                                  "     idBrewery"
                                  "     title"
                                  "     content"
                                  "     imagePath"
                                  "     rating"
                                  "     time"
                                  "     thumbsups {"
                                  "       user {"
                                  "         cip"
                                  "         name"
                                  "         surname"
                                  "       }"
                                  "     }"
                                  "		}"
                                  "		beerReviewsThumbsupBy {"
                                  "			idBeerReview"
                                  "     user {"
                                  "       cip"
                                  "       name"
                                  "       surname"
                                  "     }"
                                  "     idBeer"
                                  "     title"
                                  "     content"
                                  "     imagePath"
                                  "     rating"
                                  "     time"
                                  "     thumbsups {"
                                  "       user {"
                                  "         cip"
                                  "         name"
                                  "         surname"
                                  "       }"
                                  "     }"
                                  "		}"
                                  "	}"
                                  "}")
          expected-response (long-str "{"
                                      "  \"data\": {"
                                      "    \"profile\": {"
                                      "      \"user\": {"
                                      "        \"cip\": \"mahm1904\","
                                      "        \"name\": \"Marc-Antoine\","
                                      "        \"surname\": \"Maheux\""
                                      "      },"
                                      "      \"breweryReviewedBy\": ["
                                      "        {"
                                      "          \"brewery\": {"
                                      "            \"id\": 6,"
                                      "            \"name\": \"SherBroue\","
                                      "            \"description\": \"Génie Sherbrooke!!!\","
                                      "            \"imagePath\": \"http:\\/\\/sherbroue.ca\\/accueil\\/wp-content\\/uploads\\/2012\\/02\\/Couverture-Facebook-1.jpg\","
                                      "            \"tags\": ["
                                      "              {"
                                      "                \"id\": 2,"
                                      "                \"name\": \"Artisanale\""
                                      "              }"
                                      "            ],"
                                      "            \"rating\": 4.0"
                                      "          },"
                                      "          \"review\": {"
                                      "            \"idBreweryReview\": 4,"
                                      "            \"user\": {"
                                      "              \"cip\": \"mahm1904\","
                                      "              \"name\": \"Marc-Antoine\","
                                      "              \"surname\": \"Maheux\""
                                      "            },"
                                      "            \"idBrewery\": 6,"
                                      "            \"title\": \"Encouragement!!!\","
                                      "            \"content\": \"Vive génie sherbrooke!!!\","
                                      "            \"imagePath\": null,"
                                      "            \"rating\": 4.0,"
                                      "            \"time\": \"2018-06-10 10:00:03.0\","
                                      "            \"thumbsups\": ["
                                      "              {"
                                      "                \"user\": {"
                                      "                  \"cip\": \"pele1704\","
                                      "                  \"name\": \"Étienne\","
                                      "                  \"surname\": \"Pelletier\""
                                      "                }"
                                      "              }"
                                      "            ]"
                                      "          }"
                                      "        }"
                                      "      ],"
                                      "      \"beerReviewedBy\": ["
                                      "        {"
                                      "          \"beer\": {"
                                      "            \"id\": 5,"
                                      "            \"name\": \"Ingénieuse\","
                                      "            \"description\": \"Bière collaborative.\","
                                      "            \"ibu\": 17,"
                                      "            \"alcoholPercent\": 5.1,"
                                      "            \"imagePath\": \"https:\\/\\/cdn.narcity.com\\/uploads\\/249500_90d9f57c70a3e15b6e0a08e67dcf1d944038212a.jpg\","
                                      "            \"breweries\": ["
                                      "              {"
                                      "                \"id\": 5,"
                                      "                \"name\": \"Siboire\","
                                      "                \"description\": \"Une brasserie de Sherbrooke.\","
                                      "                \"imagePath\": \"http:\\/\\/www.ambq.ca\\/mod\\/file\\/MembreFile\\/c45147dee729311ef5b5c3003946c48f.png\","
                                      "                \"tags\": ["
                                      "                  {"
                                      "                    \"id\": 2,"
                                      "                    \"name\": \"Artisanale\""
                                      "                  }"
                                      "                ],"
                                      "                \"rating\": 4.5"
                                      "              },"
                                      "              {"
                                      "                \"id\": 6,"
                                      "                \"name\": \"SherBroue\","
                                      "                \"description\": \"Génie Sherbrooke!!!\","
                                      "                \"imagePath\": \"http:\\/\\/sherbroue.ca\\/accueil\\/wp-content\\/uploads\\/2012\\/02\\/Couverture-Facebook-1.jpg\","
                                      "                \"tags\": ["
                                      "                  {"
                                      "                    \"id\": 2,"
                                      "                    \"name\": \"Artisanale\""
                                      "                  }"
                                      "                ],"
                                      "                \"rating\": 4.0"
                                      "              }"
                                      "            ],"
                                      "            \"tags\": ["
                                      "              {"
                                      "                \"id\": 2,"
                                      "                \"name\": \"Artisanale\""
                                      "              },"
                                      "              {"
                                      "                \"id\": 4,"
                                      "                \"name\": \"Mauvais choix\""
                                      "              }"
                                      "            ],"
                                      "            \"rating\": 3.0,"
                                      "            \"style\": {"
                                      "              \"id\": 4,"
                                      "              \"name\": \"Irish ale\""
                                      "            }"
                                      "          },"
                                      "          \"review\": {"
                                      "            \"idBeerReview\": 4,"
                                      "            \"user\": {"
                                      "              \"cip\": \"mahm1904\","
                                      "              \"name\": \"Marc-Antoine\","
                                      "              \"surname\": \"Maheux\""
                                      "            },"
                                      "            \"idBeer\": 5,"
                                      "            \"title\": \"Je n'aime pas la bière, mais ça se boit!!\","
                                      "            \"content\": \"Ça se vend au Siboire... Je suis con c'est écrit dans la description.\","
                                      "            \"imagePath\": null,"
                                      "            \"rating\": 1.5,"
                                      "            \"time\": \"2018-06-10 10:00:03.0\","
                                      "            \"thumbsups\": ["
                                      "              {"
                                      "                \"user\": {"
                                      "                  \"cip\": \"pele1704\","
                                      "                  \"name\": \"Étienne\","
                                      "                  \"surname\": \"Pelletier\""
                                      "                }"
                                      "              }"
                                      "            ]"
                                      "          }"
                                      "        }"
                                      "      ],"
                                      "      \"breweryReviewsCommentedBy\": ["
                                      "        {"
                                      "          \"breweryReview\": {"
                                      "            \"idBreweryReview\": 5,"
                                      "            \"user\": {"
                                      "              \"cip\": \"parp2009\","
                                      "              \"name\": \"Pierre\","
                                      "              \"surname\": \"Parrat\""
                                      "            },"
                                      "            \"idBrewery\": 5,"
                                      "            \"title\": \"Bonne bouffe!!\","
                                      "            \"content\": \"Le Mac&Cheese est super.\","
                                      "            \"imagePath\": null,"
                                      "            \"rating\": 5.0,"
                                      "            \"time\": \"2018-06-10 10:00:04.0\","
                                      "            \"thumbsups\": ["
                                      "              {"
                                      "                \"user\": {"
                                      "                  \"cip\": \"mahm1904\","
                                      "                  \"name\": \"Marc-Antoine\","
                                      "                  \"surname\": \"Maheux\""
                                      "                }"
                                      "              }"
                                      "            ]"
                                      "          },"
                                      "          \"comment\": {"
                                      "            \"idBreweryReviewComment\": 4,"
                                      "            \"idBreweryReview\": 5,"
                                      "            \"user\": {"
                                      "              \"cip\": \"mahm1904\","
                                      "              \"name\": \"Marc-Antoine\","
                                      "              \"surname\": \"Maheux\""
                                      "            },"
                                      "            \"content\": \"Party!!!\","
                                      "            \"time\": \"2018-06-10 10:00:13.0\""
                                      "          }"
                                      "        }"
                                      "      ],"
                                      "      \"beerReviewsCommentedBy\": ["
                                      "        {"
                                      "          \"beerReview\": {"
                                      "            \"idBeerReview\": 3,"
                                      "            \"user\": {"
                                      "              \"cip\": \"lara2318\","
                                      "              \"name\": \"Andy\","
                                      "              \"surname\": \"Larochelle\""
                                      "            },"
                                      "            \"idBeer\": 4,"
                                      "            \"title\": \"Que c'est bon!!\","
                                      "            \"content\": \"C'est pas pire pour une soirée entre boux!!\","
                                      "            \"imagePath\": null,"
                                      "            \"rating\": 4.5,"
                                      "            \"time\": \"2018-06-10 10:00:02.0\","
                                      "            \"thumbsups\": ["
                                      "              {"
                                      "                \"user\": {"
                                      "                  \"cip\": \"dald2202\","
                                      "                  \"name\": \"David\","
                                      "                  \"surname\": \"Dallaire\""
                                      "                }"
                                      "              }"
                                      "            ]"
                                      "          },"
                                      "          \"comment\": {"
                                      "            \"idBeerReviewComment\": 3,"
                                      "            \"idBeerReview\": 3,"
                                      "            \"user\": {"
                                      "              \"cip\": \"mahm1904\","
                                      "              \"name\": \"Marc-Antoine\","
                                      "              \"surname\": \"Maheux\""
                                      "            },"
                                      "            \"content\": \"Peut-être que j'aimerais ça!\","
                                      "            \"time\": \"2018-06-10 10:00:12.0\""
                                      "          }"
                                      "        }"
                                      "      ],"
                                      "      \"breweryReviewsThumbsupBy\": ["
                                      "        {"
                                      "          \"idBreweryReview\": 5,"
                                      "          \"user\": {"
                                      "            \"cip\": \"parp2009\","
                                      "            \"name\": \"Pierre\","
                                      "            \"surname\": \"Parrat\""
                                      "          },"
                                      "          \"idBrewery\": 5,"
                                      "          \"title\": \"Bonne bouffe!!\","
                                      "          \"content\": \"Le Mac&Cheese est super.\","
                                      "          \"imagePath\": null,"
                                      "          \"rating\": 5.0,"
                                      "          \"time\": \"2018-06-10 10:00:04.0\","
                                      "          \"thumbsups\": ["
                                      "            {"
                                      "              \"user\": {"
                                      "                \"cip\": \"mahm1904\","
                                      "                \"name\": \"Marc-Antoine\","
                                      "                \"surname\": \"Maheux\""
                                      "              }"
                                      "            }"
                                      "          ]"
                                      "        }"
                                      "      ],"
                                      "      \"beerReviewsThumbsupBy\": ["
                                      "        {"
                                      "          \"idBeerReview\": 5,"
                                      "          \"user\": {"
                                      "            \"cip\": \"parp2009\","
                                      "            \"name\": \"Pierre\","
                                      "            \"surname\": \"Parrat\""
                                      "          },"
                                      "          \"idBeer\": 1,"
                                      "          \"title\": \"Un autre truc pas bon!\","
                                      "          \"content\": \"CE N'EST PAS BON...\","
                                      "          \"imagePath\": null,"
                                      "          \"rating\": 2.0,"
                                      "          \"time\": \"2018-06-10 10:00:04.0\","
                                      "          \"thumbsups\": ["
                                      "            {"
                                      "              \"user\": {"
                                      "                \"cip\": \"mahm1904\","
                                      "                \"name\": \"Marc-Antoine\","
                                      "                \"surname\": \"Maheux\""
                                      "              }"
                                      "            }"
                                      "          ]"
                                      "        }"
                                      "      ]"
                                      "    }"
                                      "  }"
                                      "}")
          response (execute-graphql-query graphql-query)]
      (is (is-data-equal response expected-response)))))
