(ns beerpressure.db.review.beer-review-test
  (:require [clojure.test :refer :all]
            [beerpressure.handler :refer :all]
            [beerpressure.db.common-test :refer :all]))

(use-fixtures :once db-setup-with-logged-user-fixture)

(deftest test-resolve-beer-review
  (testing "beerReview(idBeerReview: 6)"
    (let [graphql-query (long-str "{"
                                  "  beerReview(idBeerReview: 6) {"
                                  "    idBeerReview"
                                  "    cip"
                                  "    idBeer"
                                  "    title"
                                  "    content"
                                  "    imagePath"
                                  "    rating"
                                  "    time"
                                  "    thumbsups {"
                                  "      user {"
                                  "        cip"
                                  "        name"
                                  "        surname"
                                  "      }"
                                  "    }"
                                  "  }"
                                  "}")
          expected-response (long-str "{"
                                      " \"data\": {"
                                      "   \"beerReview\": {"
                                      "     \"idBeerReview\": 6,"
                                      "     \"cip\": \"pele1704\","
                                      "     \"idBeer\": 4,"
                                      "     \"title\": \"Tu as raison Andy!!\","
                                      "     \"content\": \"Damn... c'est un review, pas un commentaire...\","
                                      "     \"imagePath\": \"https:\\/\\/www.google.com\\/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjn1Pr_wLPbAhXKtlkKHX7EBJAQjRx6BAgBEAU&url=http%3A%2F%2Fknowyourmeme.com%2Fphotos%2F56807-fail-epic-fail&psig=AOvVaw3HfgoRpGtV9HRR5-0cLFJ0&ust=1527978321220516\","
                                      "     \"rating\": 4.0,"
                                      "     \"time\": \"2018-06-10 10:00:05.0\","
                                      "     \"thumbsups\": ["
                                      "       {"
                                      "         \"user\": {"
                                      "           \"cip\": \"alig2503\"",
                                      "           \"name\": \"Gaétan\","
                                      "           \"surname\": \"Allano\""
                                      "         }"
                                      "       }"
                                      "     ]"
                                      "   }"
                                      " }"
                                      "}")
          response (execute-graphql-query graphql-query)]
      (is (is-data-equal response expected-response)))))

(deftest test-resolve-beer-reviews
  (testing "beerReviews(skip: 4, first: 3, orderBy: TIME, orderType: ASC)"
    (let [graphql-query (long-str "{"
                                  "  beerReviews(skip: 4, first: 3, orderBy: TIME, orderType: ASC) {"
                                  "    idBeerReview"
                                  "    cip"
                                  "    idBeer"
                                  "    title"
                                  "    content"
                                  "    imagePath"
                                  "    rating"
                                  "    time"
                                  "    thumbsups {"
                                  "      user {"
                                  "        cip"
                                  "        name"
                                  "        surname"
                                  "      }"
                                  "    }"
                                  "  }"
                                  "}")
          expected-response (long-str "{"
                                      " \"data\": {"
                                      "   \"beerReviews\": ["
                                      "     {"
                                      "       \"idBeerReview\": 5,"
                                      "       \"cip\": \"parp2009\","
                                      "       \"idBeer\": 1,"
                                      "       \"title\": \"Un autre truc pas bon!\","
                                      "       \"content\": \"CE N'EST PAS BON...\","
                                      "       \"imagePath\": null,"
                                      "       \"rating\": 2.0,"
                                      "       \"time\": \"2018-06-10 10:00:04.0\","
                                      "       \"thumbsups\": ["
                                      "         {"
                                      "           \"user\": {"
                                      "             \"cip\": \"mahm1904\"",
                                      "             \"name\": \"Marc-Antoine\","
                                      "             \"surname\": \"Maheux\""
                                      "           }"
                                      "         }"
                                      "       ]"
                                      "     },"
                                      "     {"
                                      "       \"idBeerReview\": 6,"
                                      "       \"cip\": \"pele1704\","
                                      "       \"idBeer\": 4,"
                                      "       \"title\": \"Tu as raison Andy!!\","
                                      "       \"content\": \"Damn... c'est un review, pas un commentaire...\","
                                      "       \"imagePath\": \"https:\\/\\/www.google.com\\/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjn1Pr_wLPbAhXKtlkKHX7EBJAQjRx6BAgBEAU&url=http%3A%2F%2Fknowyourmeme.com%2Fphotos%2F56807-fail-epic-fail&psig=AOvVaw3HfgoRpGtV9HRR5-0cLFJ0&ust=1527978321220516\","
                                      "       \"rating\": 4.0,"
                                      "       \"time\": \"2018-06-10 10:00:05.0\","
                                      "       \"thumbsups\": ["
                                      "         {"
                                      "           \"user\": {"
                                      "             \"cip\": \"alig2503\"",
                                      "             \"name\": \"Gaétan\","
                                      "             \"surname\": \"Allano\""
                                      "           }"
                                      "         }"
                                      "       ]"
                                      "     },"
                                      "     {"
                                      "       \"idBeerReview\": 7,"
                                      "       \"cip\": \"royj1933\","
                                      "       \"idBeer\": 4,"
                                      "       \"title\": \"Époustouflant!!!\","
                                      "       \"content\": \"Je n'ai pas d'autre\","
                                      "       \"imagePath\": null,"
                                      "       \"rating\": 5.0,"
                                      "       \"time\": \"2018-06-10 10:00:06.0\","
                                      "       \"thumbsups\": ["
                                      "         {"
                                      "           \"user\": {"
                                      "             \"cip\": \"parp2009\"",
                                      "             \"name\": \"Pierre\","
                                      "             \"surname\": \"Parrat\""
                                      "           }"
                                      "         }"
                                      "       ]"
                                      "     }"
                                      "   ]"
                                      " }"
                                      "}")
          response (execute-graphql-query graphql-query)]
      (is (is-data-equal response expected-response))))
  (testing "beerReviews(skip: 0, first: 1, orderBy: TIME, orderType: ASC)"
    (let [graphql-query (long-str "{"
                                  "  beerReviews(skip: 0, first: 1, orderBy: TIME, orderType: ASC) {"
                                  "    idBeerReview"
                                  "  }"
                                  "}")
          expected-response (long-str "{"
                                      " \"data\": {"
                                      "   \"beerReviews\": ["
                                      "     {"
                                      "       \"idBeerReview\": 1"
                                      "     }"
                                      "   ]"
                                      " }"
                                      "}")
          response (execute-graphql-query graphql-query)]
      (is (is-data-equal response expected-response))))
  (testing "beerReviews(skip: 0, first: 1, orderBy: TIME, orderType: DESC)"
    (let [graphql-query (long-str "{"
                                  "  beerReviews(skip: 0, first: 1, orderBy: TIME, orderType: DESC) {"
                                  "    idBeerReview"
                                  "  }"
                                  "}")
          expected-response (long-str "{"
                                      " \"data\": {"
                                      "   \"beerReviews\": ["
                                      "     {"
                                      "       \"idBeerReview\": 7"
                                      "     }"
                                      "   ]"
                                      " }"
                                      "}")
          response (execute-graphql-query graphql-query)]
      (is (is-data-equal response expected-response))))
  (testing "beerReviews(skip: 0, first: 10, orderBy: TIME, orderType: ASC, beers: [1,3])"
    (let [graphql-query (long-str "{"
                                  "  beerReviews(skip: 0, first: 10, orderBy: TIME, orderType: ASC, beers: [1,3]) {"
                                  "    idBeerReview"
                                  "  }"
                                  "}")
          expected-response (long-str "{"
                                      " \"data\": {"
                                      "   \"beerReviews\": ["
                                      "     {"
                                      "       \"idBeerReview\": 1"
                                      "     },"
                                      "     {"
                                      "       \"idBeerReview\": 2"
                                      "     },"
                                      "     {"
                                      "       \"idBeerReview\": 5"
                                      "     }"
                                      "   ]"
                                      " }"
                                      "}")
          response (execute-graphql-query graphql-query)]
      (is (is-data-equal response expected-response))))
  (testing "beerReviews(skip: 0, first: 10, orderBy: TIME, orderType: ASC, cips: [\\\"mahm1904\\\",\\\"dald2202\\\"])"
    (let [graphql-query (long-str "{"
                                  "  beerReviews(skip: 0, first: 10, orderBy: TIME, orderType: ASC, cips: [\\\"mahm1904\\\",\\\"dald2202\\\"]) {"
                                  "    idBeerReview"
                                  "  }"
                                  "}")
          expected-response (long-str "{"
                                      " \"data\": {"
                                      "   \"beerReviews\": ["
                                      "     {"
                                      "       \"idBeerReview\": 2"
                                      "     },"
                                      "     {"
                                      "       \"idBeerReview\": 4"
                                      "     }"
                                      "   ]"
                                      " }"
                                      "}")
          response (execute-graphql-query graphql-query)]
      (is (is-data-equal response expected-response))))
  (testing "beerReviews(skip: 0, first: 10, orderBy: TIME, orderType: ASC, beers: [1,3], cips: [\\\"mahm1904\\\",\\\"dald2202\\\"])"
    (let [graphql-query (long-str "{"
                                  "  beerReviews(skip: 0, first: 10, orderBy: TIME, orderType: ASC, beers: [1,3], cips: [\\\"mahm1904\\\",\\\"dald2202\\\"]) {"
                                  "    idBeerReview"
                                  "  }"
                                  "}")
          expected-response (long-str "{"
                                      " \"data\": {"
                                      "   \"beerReviews\": ["
                                      "     {"
                                      "       \"idBeerReview\": 2"
                                      "     }"
                                      "   ]"
                                      " }"
                                      "}")
          response (execute-graphql-query graphql-query)]
      (is (is-data-equal response expected-response))))
  (testing "beerReviews(skip: 0, first: 1, orderBy: THUMBSUP_COUNT, orderType: ASC)"
    (let [graphql-query (long-str "{"
                                  "  beerReviews(skip: 0, first: 1, orderBy: THUMBSUP_COUNT, orderType: ASC) {"
                                  "    idBeerReview"
                                  "  }"
                                  "}")
          expected-response (long-str "{"
                                      " \"data\": {"
                                      "   \"beerReviews\": ["
                                      "     {"
                                      "       \"idBeerReview\": 2"
                                      "     }"
                                      "   ]"
                                      " }"
                                      "}")
          response (execute-graphql-query graphql-query)]
      (is (is-data-equal response expected-response))))
  (testing "beerReviews(skip: 0, first: 1, orderBy: THUMBSUP_COUNT, orderType: DESC)"
    (let [graphql-query (long-str "{"
                                  "  beerReviews(skip: 0, first: 1, orderBy: THUMBSUP_COUNT, orderType: DESC) {"
                                  "    idBeerReview"
                                  "  }"
                                  "}")
          expected-response (long-str "{"
                                      " \"data\": {"
                                      "   \"beerReviews\": ["
                                      "     {"
                                      "       \"idBeerReview\": 1"
                                      "     }"
                                      "   ]"
                                      " }"
                                      "}")
          response (execute-graphql-query graphql-query)]
      (is (is-data-equal response expected-response)))))
